#!/bin/sh

niri msg event-stream | while read -r line; do
   if [[ "$line" == "Window focus changed: None" ]]; then
     echo "1"
   elif [[ "$line" == "Window focus changed: Some"* ]]; then
     echo "0"
   fi
done
